name: Build and Release
on: 
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  Build-and-Release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
      - name: Install dependencies
        run: go get .
      - name: Prepare output path
        run: mkdir output
      - name: Package and Build
        run: go build -o output
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "output/*"
          tag: v0.1.0 # TODO: update tag for each release
      


